/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Banco;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Titular;

/**
 *
 * @author Usuario
 */
public class CajeroPrestamos extends javax.swing.JPanel {

    Banco banco;
    DefaultComboBoxModel modeloComboPrestamos;

    public CajeroPrestamos(Banco banco) {
        this.banco = banco;
        inicializarModeloPrestamos();
        initComponents();
    }
    /**
     * Inicializa el modelo del combo box con solo los titulares con prestamos a su cargo.
     */
    private void inicializarModeloPrestamos() {
        modeloComboPrestamos = new DefaultComboBoxModel();

        for (Titular titular : banco.getTitulares()) {
            if (titular.getPrestamo().isActivo()) {
                modeloComboPrestamos.addElement(titular);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPago = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbTitulares = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtPrestamo = new javax.swing.JTextField();
        txtInteres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(850, 480));

        btnPago.setText("Validar Pago");
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        jLabel1.setText("Titular");

        cmbTitulares.setModel(modeloComboPrestamos);
        cmbTitulares.setSelectedIndex(-1);
        cmbTitulares.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTitularesItemStateChanged(evt);
            }
        });

        jLabel2.setText("Importe Prestamo");

        txtPrestamo.setEditable(false);

        txtInteres.setEditable(false);

        jLabel3.setText("Interés");

        jLabel4.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha)
                            .addComponent(txtInteres, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrestamo)
                            .addComponent(cmbTitulares, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTitulares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(61, 61, 61)
                .addComponent(btnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        validarPrestamo();
    }//GEN-LAST:event_btnPagoActionPerformed

    private void cmbTitularesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTitularesItemStateChanged
        cargarPrestamo();
    }//GEN-LAST:event_cmbTitularesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPago;
    private javax.swing.JComboBox<String> cmbTitulares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtPrestamo;
    // End of variables declaration//GEN-END:variables

    /**
     * Valida el préstamo.
     */
    private void validarPrestamo() {
        Titular titular = (Titular) cmbTitulares.getSelectedItem();
        titular.getPrestamo().setActivo(false);
    }

    /**
     * Muestra una ventana de informacion con un determinado titulo y mensaje.
     *
     * @param mensaje Mensaje de la ventana.
     * @param titulo Titulo de la ventana.
     */
    public void ventanaInformacion(String mensaje, String titulo) {
        String rutaImagen = "src/images/informacion.png";
        ImageIcon icono = new ImageIcon(rutaImagen);
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.WARNING_MESSAGE, icono);
    }

    /**
     * Carga los datos del préstamo de un titular.
     */
    private void cargarPrestamo() {
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("d/M/y");
        Titular titular = (Titular) cmbTitulares.getSelectedItem();

        txtPrestamo.setText(Double.toString(titular.getPrestamo().getMonto()));
        txtInteres.setText(Double.toString(titular.getPrestamo().getTasaInteres()));
        txtFecha.setText(titular.getPrestamo().getPlazo().format(formatoFecha));

    }
}
