/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author dam
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Ventana() {
        initComponents();
        jMenuBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTitulares = new javax.swing.JMenu();
        mnuAltaTitulares = new javax.swing.JMenuItem();
        mnuConsultaTitulares = new javax.swing.JMenuItem();
        mnuModificacionTitulares = new javax.swing.JMenuItem();
        mnuAperturaCuentas = new javax.swing.JMenu();
        mnuGestionPrestamos = new javax.swing.JMenu();
        mnuTransacciones = new javax.swing.JMenu();
        mnuIngresarTransacciones = new javax.swing.JMenuItem();
        mnuRetirarTransacciones = new javax.swing.JMenuItem();
        mnuConsultaTransacciones = new javax.swing.JMenuItem();
        mnuPrestamos = new javax.swing.JMenu();
        mnuEstadoPrestamos = new javax.swing.JMenuItem();
        mnuValidarPrestamos = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(850, 480));

        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 30));

        mnuTitulares.setText("Titulares");
        mnuTitulares.setFocusable(false);

        mnuAltaTitulares.setText("Alta");
        mnuTitulares.add(mnuAltaTitulares);

        mnuConsultaTitulares.setText("Consulta");
        mnuConsultaTitulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaTitularesActionPerformed(evt);
            }
        });
        mnuTitulares.add(mnuConsultaTitulares);

        mnuModificacionTitulares.setText("Modificacion");
        mnuTitulares.add(mnuModificacionTitulares);

        jMenuBar1.add(mnuTitulares);

        mnuAperturaCuentas.setText("Apertura de Cuentas");
        jMenuBar1.add(mnuAperturaCuentas);

        mnuGestionPrestamos.setText("Gestion de préstamos");
        jMenuBar1.add(mnuGestionPrestamos);

        mnuTransacciones.setText("Transacciones");

        mnuIngresarTransacciones.setText("Ingresar");
        mnuTransacciones.add(mnuIngresarTransacciones);

        mnuRetirarTransacciones.setText("Retirar");
        mnuTransacciones.add(mnuRetirarTransacciones);

        mnuConsultaTransacciones.setText("Consulta");
        mnuTransacciones.add(mnuConsultaTransacciones);

        jMenuBar1.add(mnuTransacciones);

        mnuPrestamos.setText("Prestamos");

        mnuEstadoPrestamos.setText("Estado");
        mnuPrestamos.add(mnuEstadoPrestamos);

        mnuValidarPrestamos.setText("Validar");
        mnuPrestamos.add(mnuValidarPrestamos);

        jMenuBar1.add(mnuPrestamos);

        mnuCerrarSesion.setText("Cerrar sesión");
        jMenuBar1.add(mnuCerrarSesion);

        mnuSalir.setText("Salir");
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuConsultaTitularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaTitularesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuConsultaTitularesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAltaTitulares;
    private javax.swing.JMenu mnuAperturaCuentas;
    private javax.swing.JMenu mnuCerrarSesion;
    private javax.swing.JMenuItem mnuConsultaTitulares;
    private javax.swing.JMenuItem mnuConsultaTransacciones;
    private javax.swing.JMenuItem mnuEstadoPrestamos;
    private javax.swing.JMenu mnuGestionPrestamos;
    private javax.swing.JMenuItem mnuIngresarTransacciones;
    private javax.swing.JMenuItem mnuModificacionTitulares;
    private javax.swing.JMenu mnuPrestamos;
    private javax.swing.JMenuItem mnuRetirarTransacciones;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuTitulares;
    private javax.swing.JMenu mnuTransacciones;
    private javax.swing.JMenuItem mnuValidarPrestamos;
    // End of variables declaration//GEN-END:variables
}
